---
platforms:
  - name: archlinux
    groups:
      - vault_raft_servers
    image: carlodepieri/docker-archlinux-ansible
    command: /lib/systemd/systemd
    privileged: true
    capabilities:
      - SYS_ADMIN
      - CAP_IPC_LOCK
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro

provisioner:
  playbooks:
    prepare: prepare.yml
