---
- name: Prepare
  hosts: all

  tasks:
    - name: Install prerequisites
      package:
        name:
          - sudo
          - unzip
          - tar
        state: present

    - name: Install OS packages on controlling host
      when: ansible_distribution != 'MacOSX'
      package:
        name: unzip
      become: true
      delegate_to: localhost

    - name: Install netaddr dependency on controlling host
      pip:
        name: netaddr
      become: false
      delegate_to: localhost
