---
- name: Prepare
  hosts: all

  tasks:
    - name: Install prerequisites
      package:
        name:
          - sudo
          - unzip
          - tar
        state: present

    - name: Install netaddr dependency on controlling host
      pip:
        name: netaddr
      become: false
      delegate_to: localhost
