---
platforms:
  - name: vault-centos-7
    groups:
      - vault_raft_servers
    image: milcom/centos7-systemd
    privileged: true
    dockerfile: ../_shared/Dockerfile.j2
    capabilities:
      - SYS_ADMIN
      - CAP_IPC_LOCK
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
