---
platforms:
  - name: centos-7
    groups:
      - vault_raft_servers
    image: milcom/centos7-systemd
    pre_build_image: true
    privileged: true
    capabilities:
      - SYS_ADMIN
      - CAP_IPC_LOCK
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
  - name: centos-7_repo
    groups:
      - vault_raft_servers
    image: milcom/centos7-systemd
    pre_build_image: true
    privileged: true
    capabilities:
      - SYS_ADMIN
      - CAP_IPC_LOCK
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro

provisioner:
  inventory:
    host_vars:
      centos-7_repo:
        vault_install_hashi_repo: true
        vault_bin_path: /usr/bin
  playbooks:
    prepare: prepare.yml
