---
platforms:
  - name: centos-7
    groups:
      - vault_raft_servers
    image: dokken/centos-7
    dockerfile: ../_shared/Dockerfile.j2
    capabilities:
      - SYS_ADMIN
      - CAP_IPC_LOCK
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
  - name: centos-7_repo
    groups:
      - vault_raft_servers
    image: dokken/centos-7
    dockerfile: ../_shared/Dockerfile.j2
    capabilities:
      - SYS_ADMIN
      - CAP_IPC_LOCK
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro

provisioner:
  inventory:
    host_vars:
      centos-7_repo:
        vault_install_hashi_repo: true
        vault_bin_path: /usr/bin
