---
platforms:
  - name: centos-7
    groups:
      - vault_raft_servers
    image: dokken/centos-7
    #  command: /lib/systemd/systemd
    #    entrypoint: /usr//lib/systemd/systemd
    dockerfile: Dockerfile.j2
    pre_build_image: true
    recreate: true
    privileged: true
    cgroup_parent: docker.slice
    #    tmpfs:
    #      - /run
    #      - /tmp
    capabilities:
      - SYS_ADMIN
      - CAP_IPC_LOCK
      # volumes:
      #   # - /sys/fs/cgroup:/sys/fs/cgroup:rw
      #   - /sys/fs/cgroup:/sys/fs/cgroup:ro
  - name: centos-7_repo
    groups:
      - vault_raft_servers
    image: dokken/centos-7
    # entrypoint: /usr/lib/systemd/systemd
    dockerfile: Dockerfile.j2
    pre_build_image: false
    recreate: true
    privileged: true
    cgroup_parent: docker.slice
    # tmpfs:
    #  - /run
    # - /tmp
    capabilities:
      - SYS_ADMIN
      - CAP_IPC_LOCK
      # volumes:
      #   # - /sys/fs/cgroup:/sys/fs/cgroup:rw
      #   - /sys/fs/cgroup:/sys/fs/cgroup:ro

provisioner:
  inventory:
    host_vars:
      centos-7_repo:
        vault_install_hashi_repo: true
        vault_bin_path: /usr/bin
        #  playbooks:
        #    prepare: prepare.yml
