---
- name: Prepare controlling host
  hosts: localhost
  connection: local

  tasks:
    - name: Prepare CI environment
      when: (lookup('env', 'CI'))
      block:
        - name: Install OS packages on controlling host
          when: ansible_distribution != 'MacOSX'
          package:
            name: unzip
          become: true

        - name: Install netaddr dependency on controlling host
          pip:
            name: netaddr
          become: false

- name: Prepare CentOS 7
  hosts: all

  tasks:
    - name: Add systemd-backports repo
      yum_repository:
        name: "copr:copr.fedorainfracloud.org:jsynacek:systemd-backports-for-centos-7"
        description: "Copr repo for systemd-backports-for-centos-7 owned by jsynacek"
        baseurl: "https://download.copr.fedorainfracloud.org/results/jsynacek/systemd-backports-for-centos-7/epel-7-$basearch/"
        file: jsynacek-systemd-backports-for-centos-7-epel-7
        skip_if_unavailable: true
        gpgcheck: true
        gpgcakey: https://download.copr.fedorainfracloud.org/results/jsynacek/systemd-backports-for-centos-7/pubkey.gpg
        repo_gpgcheck: false
        enabled: true

    - name: Update systemd  # noqa package-latest
      package:
        name: systemd
        state: latest
