---
platforms:
  - name: ubuntu-18.04
    groups:
      - vault_raft_servers
    image: dokken/ubuntu-18.04
    pre_build_image: true
    command: /lib/systemd/systemd
    privileged: true
    capabilities:
      - SYS_ADMIN
      - CAP_IPC_LOCK
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
  - name: ubuntu-18.04_repo
    groups:
      - vault_raft_servers
    image: dokken/ubuntu-18.04
    pre_build_image: true
    command: /lib/systemd/systemd
    privileged: true
    capabilities:
      - SYS_ADMIN
      - CAP_IPC_LOCK
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro

provisioner:
  inventory:
    host_vars:
      ubuntu-18.04_repo:
        vault_install_hashi_repo: true
        vault_bin_path: /usr/bin
