---
platforms:
  - name: centos-6
    groups:
      - vault_raft_servers
    image: dokken/centos-6
    dockerfile: ../_shared/Dockerfile.j2
    privileged: true
    capabilities:
      - SYS_ADMIN
      - CAP_IPC_LOCK
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
  - name: centos-6_repo
    groups:
      - vault_raft_servers
    image: dokken/centos-6
    dockerfile: ../_shared/Dockerfile.j2
    privileged: true
    capabilities:
      - SYS_ADMIN
      - CAP_IPC_LOCK
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro

provisioner:
  inventory:
    group_vars:
      all:
        ansible_python_interpreter: /opt/rh/rh-python36/root/usr/bin/python
    host_vars:
      centos-6_repo:
        vault_install_hashi_repo: true
        vault_bin_path: /usr/bin
  playbooks:
    prepare: prepare.yml
