---
- name: Prepare
  hosts: all
  gather_facts: false

  tasks:
    - name: Add Software Collections Repository
      raw: yum install -y centos-release-scl
      changed_when: false

    - name: Fix EOL CentOS 6 mirrors
      raw: sed -i -e 's/^mirrorlist/#mirrorlist/g' -e
            's/^#\s\?baseurl=http:\/\/mirror.centos.org\/centos\/\($releasever\|6\)\//baseurl=http:\/\/vault.centos.org\/6.10\//g' /etc/yum.repos.d/*.repo
      changed_when: false

    - name: Install python 3.6
      raw: yum install -y rh-python36
      changed_when: false

    - name: Install OS packages on controlling host
      when: ansible_distribution != 'MacOSX'
      package:
        name: unzip
      become: true
      delegate_to: localhost

    - name: Install netaddr dependency on controlling host
      pip:
        name: netaddr
      become: false
      delegate_to: localhost
