---
- name: Prepare controlling host
  hosts: localhost
  connection: local

  tasks:
    - name: Install OS packages on controlling host
      when: ansible_distribution != 'MacOSX'
      package:
        name: unzip
      become: true

    - name: Install netaddr dependency on controlling host
      pip:
        name: netaddr
      become: false

- name: Prepare CentOS 6
  hosts: all
  gather_facts: false

  tasks:
    - name: Add Software Collections Repository
      raw: yum install -y centos-release-scl
      changed_when: false

    - name: Fix EOL CentOS 6 mirrors
      raw: sed -i -e 's/^mirrorlist/#mirrorlist/g' -e
            's/^#\s\?baseurl=http:\/\/mirror.centos.org\/centos\/\($releasever\|6\)\//baseurl=http:\/\/vault.centos.org\/6.10\//g' /etc/yum.repos.d/*.repo
      changed_when: false

    - name: Install python 2.7
      raw: yum install -y python27
      changed_when: false
