---
- name: Prepare
  hosts: all
  gather_facts: false

  tasks:
    - name: Add Software Collections Repository
      raw: yum install -y centos-release-scl
      changed_when: false

    - name: Install python 3.6
      raw: yum install -y rh-python36
      changed_when: false

    - name: Install netaddr dependency on controlling host
      pip:
        name: netaddr
      become: false
      delegate_to: localhost
