---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  set -e
  yamllint .
  ansible-lint
provisioner:
  name: ansible
  config_options:
    defaults:
      callbacks_enabled: timer,profile_tasks
      fact_caching: jsonfile
      fact_caching_connection: ./cache
      forks: 100
    connection:
      pipelining: true
  playbooks:
    prepare: ../_shared/prepare.yml
    converge: ../_shared/converge.yml
    verify: ../_shared/verify.yml
verifier:
  name: ansible
