---
platforms:
  - name: debian-10
    groups:
      - vault_raft_servers
    image: dokken/debian-10
    command: /lib/systemd/systemd
    privileged: true
    capabilities:
      - SYS_ADMIN
      - CAP_IPC_LOCK
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
  - name: debian-10_repo
    groups:
      - vault_raft_servers
    image: dokken/debian-10
    command: /lib/systemd/systemd
    privileged: true
    capabilities:
      - SYS_ADMIN
      - CAP_IPC_LOCK
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro

provisioner:
  inventory:
    host_vars:
      debian-10_repo:
        vault_install_hashi_repo: true
        vault_bin_path: /usr/bin
