---
name: Ansible Molecule

on:
  push:
    tags_ignore:
      - '*'
  pull_request:

env:
  ANSIBLE_FORCE_COLOR: '1'
  PY_COLORS: '1'

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        scenario:
          - ubuntu-18.04
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: molecule
        uses: gofrolist/molecule-action@v2
        with:
          molecule_command: lint
          molecule_args: --scenario-name ${{ matrix.scenario }}
  test:
    needs:
      - lint
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        scenario:
          - ubuntu-18.04
          - centos-7
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: molecule
        uses: gofrolist/molecule-action@v2
        with:
          molecule_command: test
          molecule_args: --scenario-name ${{ matrix.scenario }}
